### DISCUSSION TITLE
Add Lightning-Terminal

### DISCUSSION THREAD

**Discussion by astupidmoose** [btcpayserver/btcpayserver#2706] [Ideas / Feature Requests]
I've been looking for more Lightning usability around Loop since all of my loops through RTL seem to be failing and discovered that Lightning Labs actually has their own terminal for managing not only loop but also "pool". 

https://github.com/lightninglabs/lightning-terminal

> Run a single binary that integrates loopd, poold and faraday daemons all in one

I'm not sure if it possibly makes sense to replace the loop integration with this since loop is included by default as well?

This potentially adds another way of managing channels for merchants by allowing them to loop out with what seems to be a bit more of an intuitive UI but also allows merchants to "lend" or sell off their liquidity.

**Comment by dennisreimann** [comment]
Started tinkering with this, some notes for reference: We need to configure our internal LND instance as a [standalone/remote](https://github.com/lightninglabs/lightning-terminal/blob/master/doc/config-lnd-remote.md#connecting-lit-to-a-standalone-lnd-process) by passing the following config:

```conf
remote.lnd.rpcserver=lnd_bitcoin:10009
remote.lnd.macaroonpath=/data/lnd/admin.macaroon
remote.lnd.tlscertpath=/data/lnd/tls.cert
```

The docker fragment would look something like this:

```yml
version: "3"
services:
  btcpayserver:
    environment:
      BTCPAY_EXTERNALSERVICES: "Lightning Terminal:${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/lit;"
  lnd_lit:
    image: "lightninglabs/lightning-terminal:v0.5.0-alpha@sha256:00986045ec41588c55d10d170b48352c8792cea51f855b2b4c770ed91fe9852e"
    restart: unless-stopped
    expose:
      - "8443"
    volumes:
      - "lnd_lit_datadir:/data/lit"
      - "lnd_bitcoin_datadir:/data/lnd:ro"
    links:
      - lnd_bitcoin
volumes:
  lnd_lit_datadir:
required:
  - "bitcoin-lnd"
  - "opt-lnd-grpc"
```

Trying to find out how to pass our LiT config. /cc @guggero

**Reply by guggero** [reply]
That could like like this:

```yaml
version: "3"
services:
  btcpayserver:
    environment:
      BTCPAY_EXTERNALSERVICES: "Lightning Terminal:${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/lit;"
  lnd_lit:
    image: "lightninglabs/lightning-terminal:v0.5.0-alpha@sha256:00986045ec41588c55d10d170b48352c8792cea51f855b2b4c770ed91fe9852e"
    restart: unless-stopped
    expose:
      - "8443"
    volumes:
      - "lnd_lit_datadir:/data/lit"
      - "lnd_bitcoin_datadir:/data/lnd:ro"
    links:
      - lnd_bitcoin
    command:
      - "--remote.lnd.rpcserver=lnd_bitcoin:10009"
      - "--remote.lnd.macaroonpath=/data/lnd/admin.macaroon"
      - "--remote.lnd.tlscertpath=/data/lnd/tls.cert"
volumes:
  lnd_lit_datadir:
required:
  - "bitcoin-lnd"
  - "opt-lnd-grpc"
```
