### DISCUSSION TITLE
Is exposing the monero  node "publicly" by altering opt-monero-expose.yml a bad idea for some reason?

### DISCUSSION THREAD

**Discussion by sla-te** [btcpayserver/btcpayserver#3116] [Technical Support] [answered]
I found, that we can access the monero node from remote if we alter opt-monero-expose.yml as follows

```
version: "3"

services:
  monerod:
    ports:
    - "0.0.0.0:18081:18081"
required:
    - "monero"
```

Is doing this for some reason a bad idea?
