### DISCUSSION TITLE
Show note to only send from personal wallet

### DISCUSSION THREAD

**Discussion by jstrnbrg** [btcpayserver/btcpayserver#3735] [Ideas / Feature Requests]
It would be useful if the invoice page would show a note to the customer that it's recommended to only pay from a personal wallet and not use an exchange withdrawal in order to pay a BTCPAY invoice. If you do that the exchange might deduct some fees and therefore the invoice will be underpaid. 

We are currently "hacking" that note into the invoice page via the custom CSS function ;)

```css
.bp-views::before {
  content: "Please only send from your own wallet, not from an exchange";
  text-align: center;
  display: block;
}
```
