### DISCUSSION TITLE
explore all possible environment variables

### DISCUSSION THREAD

**Discussion by maipal-c** [btcpayserver/btcpayserver#6249] [Technical Support]
hey i am willing to contribute to this project by adding an k8s helm chart.

i am not sure if this contribution will be accepted or not but atleast i want to use it for my self.

initially i want to add 2 components - nbxplorer & btcpayserver [bitcoind node will be external ] & postgresql (bitnami chart) will be dependency or maybe external postgres can be provided. 

so the current questions i have like 

- can i run multiple nbxplorer pods (deployments) or do i need statefull set (statefull/persistent volume) or i cannot run it with multipal pods (high availability)
- can i run btcpayserver as deployments or do i  need statefull set (persistent volume) or i cannot run btcpay server with multiple pods (high availability)
- an reference to all possible configuration options [all env variables & all config options for a config file]. maybe link for these docs
- for best security (security context)
     ```
          capabilities:
              drop:
                 - ALL
           privileged: false
           runAsUser: 1001
           runAsGroup: 1001 
           runAsNonRoot: true
           readOnlyRootFilesystem: true
           allowPrivilegeEscalation: false
           seccompProfile:
              type: RuntimeDefault
     ```
