### DISCUSSION TITLE
[FIX PAIN] Improve products editor UX

### DISCUSSION THREAD

**Discussion by jaonoctus** [btcpayserver/btcpayserver#6431] [Ideas / Feature Requests]
Right now, If i have a big list of products in the POS app, I have to scroll all way up to edit the product I just clicked.

This box should be a drawer, a popup/modal or at least a sticky element in the screen.

![image](https://github.com/user-attachments/assets/7a7038f3-4b11-430e-9a55-f83cf50b083f)

![image](https://github.com/user-attachments/assets/13069b55-946d-4a1d-88ba-17e254cfa78d)

**Comment by jaonoctus** [comment]
This should be fixable by adding a css like this to fix it for desktop (just an PoC):

```css
#EditorTabPane > div:first-child > div:nth-child(2) {
    position: sticky;
    top: 94px;
}
```

If we add as `sticky`, we should add a internal scrollable area to the form. Or like I said, do it as a drawer or modal.

[Desktop-1732575926740.webm](https://github.com/user-attachments/assets/c3f73cd5-0c44-4e25-976e-f2e15d569812)
