### ISSUE TITLE
Postgres password are logged in clear text

### ISSUE THREAD

**Issue by tokyowizard** [btcpayserver/btcpayserver#1980]
**Describe the bug**
The Postgres password are logged in clear text.

**To Reproduce**
1. Have [docker](https://www.docker.com/) and [docker-compose](https://docs.docker.com/compose/install/) installed.
2. Put this `docker-compose.yml` file in an empty directory:
    ```
    version: "3"
    services:
      btcpayserver_test:
        image: btcpayserver/btcpayserver:1.0.5.7
        environment:
          BTCPAY_NETWORK: "regtest"
          BTCPAY_POSTGRES: "User ID=btcpayuser;Password=postgresql_password;Host=postgres;Port=5432;Database=btcpayserver"
    ```

3. Run `docker-compose up` in that directory.
4. See the Postgres password, `postgresql_password`, displayed in the logs:
    ```
    $ docker-compose up
    Creating network "x_default" with the default driver
    Creating x_btcpayserver_test_1 ... done
    Attaching to x_btcpayserver_test_1
    btcpayserver_test_1  | info: Configuration:  Data Directory: /datadir
    btcpayserver_test_1  | info: Configuration:  Configuration File: /datadir/RegTest/settings.config
    btcpayserver_test_1  | info: Configuration:  Creating configuration file
    btcpayserver_test_1  | info: Configuration:  Network: Regtest
    btcpayserver_test_1  | info: Configuration:  Supported chains: BTC
    btcpayserver_test_1  | info: Configuration:  Network: Regtest
    btcpayserver_test_1  | info: Configuration:  Supported chains: BTC
    btcpayserver_test_1  | info: Configuration:  Postgres DB used (User ID=btcpayuser;Password=postgresql_password;Host=postgres;Port=5432;Database=btcpayserver)
    ^CGracefully stopping... (press Ctrl+C again to force)
    Stopping x_btcpayserver_test_1 ... done
    ```

**Expected behavior**
Passwords are not displayed in the logs.
Logs could be sent to a central logging service for others to view these logs. So, it's a concern from a security perspective if a party got access to the logs with the sensitive data.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  [`1.0.5.7`](https://hub.docker.com/r/btcpayserver/btcpayserver/tags)
- Deployment Method: Docker
