### ISSUE TITLE
Vuejs and summernote vulnerability?

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#2856]
We got two reports of XSS (in [Point of Sale](https://huntr.dev/bounties/0fcdee5f-1f07-47ce-b650-ea8b4a7d35d8/?token=7a607e7fd66eb51ca4284358e497fd770985ceefdbd0a578361c659f71b2472d7d0a17890662a4e885214e4a137cee3132f2f0ee95eb1e757345c9f47db3cd6baa8e5b68c1312b7cbf00697a6957e782c8cd96d020c58f551392f69bf5123161b85e775c214e9032f6ed5340e3291c8e62d1ff05c03262d84d86a9165fcddd) & in [Payment Requests](https://huntr.dev/bounties/ffabdac8-7280-4806-b70c-9b0d1aafbb6e/?token=7a607e7fd66eb51ca4284358e497fd770985ceefdbd0a578361c659f71b2472d7d0a17890662a4e885214e4a137cee3132f2f0ee95eb1e757345c9f47db3cd6baa8e5b68c1312b7cbf00697a6957e782c8cd96d020c58f551392f69bf5123161b85e775c214e9032f6ed5340e3291c8e62d1ff05c03262d84d86a9165fcddd))

It seems two components are failing us: summernote and vuejs.

Both reports are subject to `summernote` issue: It is possible to execute some JS code with some carefully crafted link added with the rich editor: `"><img src=x onerror=alert(225552) ~2F>`. The fact that the JS executes right away is not the scary part. The scary part is that when it is saved, it get executed every times you run in the settings page of the payment request/point of sale.

For the `vuejs` issue, I noticed that the public view of the point of sale doesn't execute the javascript, while the public view of the payment request execute the javascript.

I was at first blaming our server side html sanitizer, but it is doing a sane job:

```
Input: <p><a href="http://&quot;><img src=x onerror=alert(225552) ~2F>" target="_blank">"&gt;<img src="x" onerror="alert(225552)" ~2f=""></a><br></p>
Output:<p><a href="http://&quot;&gt;&lt;img src=x onerror=alert(225552) ~2F&gt;" target="_blank">"&gt;<img src="x" class="img-fluid"></a><br></p>
```

If you copy the output in a HTML, you can see that it is interpreted correctly by a browser:
For example, you can see no injection in the public PoS page:

![image](https://user-images.githubusercontent.com/3020646/132352976-d2d10dcb-550f-4975-80cd-632a81eb9139.png)

However, things are different for the payment request.

![image](https://user-images.githubusercontent.com/3020646/132353183-5c56e59f-227d-422c-98cb-6318bc53d5c9.png)

If you look the server side generated HTML, you don't see the injection:

![image](https://user-images.githubusercontent.com/3020646/132353333-72e9295f-98e7-4f4f-be19-b7de871c822e.png)

I noticed that removing the `v-html` fix the bug completely. This mean that vuejs is reversing what the server-side sanitizer protected against.

I am thinking just removing any `v-html` in the solution to prevent this issue, because I don't see how we can solve the problem on any other way.

Our vuejs and summernote are almost up to date.
I tried to update vuejs, but it doesn't fix the bug. For the summernote issue, it seemed to be like [this report](https://snyk.io/vuln/SNYK-JS-SUMMERNOTE-173735), but that should have been fixed in the recent version we are using.

**Comment by NicolasDorier** [comment]
There is also another vulnerability in the [Point of sale editor](https://www.huntr.dev/bounties/32e30ecf-31fa-45f6-8552-47250ef0e613/).

Copy 

```yml
green tea:
  price: 1
  title: Green Tea
  description: "Lovely, fresh and tender, Meng Ding Gan Lu ('sweet dew') is grown in the lush Meng Ding Mountains of the southwestern province of Sichuan where it has been cultivated for over a thousand years."
  image: ~/img/pos-sample/green-tea.jpg
  custom: false
  buyButtonText: "><img src=x onerror=alert(225552) ~2F>
```
In the raw editor, save, then click on the edit button of the green tea.
