### ISSUE TITLE
Failure to start BTCPayServer post 1.4.0 upgrade

### ISSUE THREAD

**Issue by tehelsper** [btcpayserver/btcpayserver#3528]
**Describe the bug**
This bug occurs after upgrading to v1.4.x from v1.3.x and has been reported by several myNode users.

At first, I was not able to reproduce the issue, but I have since reproduced the issue on a 32-bit Raspberry Pi 4. The 64-bit device seems to run fine, but I'm not sure if that is necessarily related.

The affected users have tried downgrading back to 1.3.6, which lets it work again and re-upgrading causes it to fail.

On my device having the issue, this is all I see in the logs for the btcpayserver container:

```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
rm: cannot remove '/datadir/host_id_rsa': Device or resource busy
Creating BTCPay Server SSH key File...
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
rm: cannot remove '/datadir/host_id_rsa': Device or resource busy
Creating BTCPay Server SSH key File...
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
rm: cannot remove '/datadir/host_id_rsa': Device or resource busy
Creating BTCPay Server SSH key File...
```

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Install BTC Pay v1.4.x on myNode
2. Containers start, but don't run properly
4. Browser error because NGINX can't forward traffic to BTCPay

**Expected behavior**

I expected BTCPay to start. I'm thinking it is probably config related or related to the device being 32-bit, since that is the only place I've seen it. What I find unusual is that it seems to work fine on most devices. Not sure what could cause that.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    1.4.
- Deployment Method:        Docker
- Browser: N/A

**Setup Parameters**

env file
```
BTCPAY_PROTOCOL=https
BTCPAY_HOST=mynode.local
BTCPAY_ADDITIONAL_HOSTS=btcpay-mynode.local
BTCPAY_ANNOUNCEABLE_HOST=
REVERSEPROXY_HTTP_PORT=80
REVERSEPROXY_HTTPS_PORT=443
REVERSEPROXY_DEFAULT_HOST=none
BTCPAY_IMAGE=
ACME_CA_URI=production
NBITCOIN_NETWORK=mainnet
LETSENCRYPT_EMAIL=
LIGHTNING_ALIAS=
BTCPAY_SSHTRUSTEDFINGERPRINTS=
BTCPAY_SSHKEYFILE=/datadir/host_id_rsa
BTCPAY_SSHAUTHORIZEDKEYS=/datadir/host_authorized_keys
BTCPAY_HOST_SSHAUTHORIZEDKEYS=/root/.ssh/authorized_keys
LIBREPATRON_HOST=
BTCTRANSMUTER_HOST=
BTCPAY_CRYPTOS=btc
WOOCOMMERCE_HOST=
TOR_RELAY_NICKNAME=
TOR_RELAY_EMAIL=

# myNode Additions
BTCPAY_VERSION=1.4.5
NBXPLORER_VERSION=2.2.20
POSTGRES_VERSION=9.6.5
```

**Comment by celi28** [comment]
Looks like you `BTCPAY_SSHKEYFILE` is locked by another concurrent process.

Try to find which one by running `lsof /datadir/host_id_rsa` and kill it.
If file is opened by docker process, you should have to find a duplicate container.

**Comment by tehelsper** [comment]
Thanks for responding. So, I had thought something similar and deleted the file, remade it, compared permissions between devices and I have not found anything. No other processes appear to be using it. The file mapped in is intended to only be used for BTC Pay Server.

I ran the lsof command in the host OS and found no processes actually using it. Any other ideas?

**Comment by celi28** [comment]
Can you share your docker-compose file?

A poor man solution would be to remove BTCPAY_SSH feature and see if it solve the problem.
After upgrade, try to re-set it if you need the ssh functionality.

**Comment by tehelsper** [comment]
Sure. I've tried removing the SSH config and I added a volume for the plugins which I noticed was throwing a warning. Still no luck.

```
version: "3"
services:
  btcpayserver:
    restart: unless-stopped
    image: btcpayserver/btcpayserver:${BTCPAY_VERSION}
    network_mode: host
#    expose:
#    - "49392"
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=localhost;Port=5432;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      BTCPAY_SSHCONNECTION: "root@localhost"
      BTCPAY_SSHTRUSTEDFINGERPRINTS: ${BTCPAY_SSHTRUSTEDFINGERPRINTS}
      BTCPAY_SSHKEYFILE: ${BTCPAY_SSHKEYFILE}
      BTCPAY_SSHAUTHORIZEDKEYS: ${BTCPAY_SSHAUTHORIZEDKEYS}
      BTCPAY_DEBUGLOG: btcpay.log
      BTCPAY_DOCKERDEPLOYMENT: "true"
      BTCPAY_CHAINS: "btc"
      BTCPAY_BTCEXPLORERURL: http://localhost:32838/
      BTCPAY_BTCLIGHTNING: "type=lnd-rest;server=https://localhost:10080/;macaroonfilepath=/etc/lnd_bitcoin/data/chain/bitcoin/mainnet/admin.macaroon;allowinsecure=true"
      BTCPAY_BTCEXTERNALRTL: "server=/rtl/api/authenticate/cookie;cookiefile=/etc/lnd_bitcoin_rtl/.cookie"
      BTCPAY_BTCEXTERNALLNDGRPC: "server=/;macaroonfilepath=/etc/lnd_bitcoin/data/chain/bitcoin/mainnet/admin.macaroon;macaroondirectorypath=/etc/lnd_bitcoin/data/chain/bitcoin/mainnet/"
      BTCPAY_BTCEXTERNALLNDREST: "server=/lnd-rest/btc/;macaroonfilepath=/etc/lnd_bitcoin/data/chain/bitcoin/mainnet/admin.macaroon;macaroondirectorypath=/etc/lnd_bitcoin/data/chain/bitcoin/mainnet"
      BTCPAY_BTCEXTERNALLNDSEEDBACKUP: "/etc/lnd_bitcoin/data/chain/bitcoin/${NBITCOIN_NETWORK:-regtest}/walletunlock.json"
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 49392
      VIRTUAL_HOST: ${BTCPAY_HOST},${BTCPAY_ADDITIONAL_HOSTS}
      VIRTUAL_HOST_NAME: "btcpay"
      SSL_POLICY: Mozilla-Modern
      LETSENCRYPT_HOST: ${BTCPAY_HOST},${BTCPAY_ADDITIONAL_HOSTS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-<no value>}
    volumes:
    - "btcpay_datadir:/datadir"
    - "nbxplorer_datadir:/root/.nbxplorer"
    - "/mnt/hdd/mynode/lnd:/etc/lnd_bitcoin"
    - "/root/.ssh/authorized_keys:${BTCPAY_SSHAUTHORIZEDKEYS}"
    - "/root/.ssh/id_rsa_btcpay:${BTCPAY_SSHKEYFILE}"
    - "btcpay_pluginsdir:/root/.btcpayserver/Plugins"
  nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:${NBXPLORER_VERSION}
    network_mode: host
#    expose:
#    - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_TRIMEVENTS: 10000
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://localhost:8332/
      NBXPLORER_BTCNODEENDPOINT: localhost:8333
    volumes:
    - "nbxplorer_datadir:/datadir"




  postgres:
    restart: unless-stopped
    image: btcpayserver/postgres:${POSTGRES_VERSION}
    network_mode: host
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
    - "postgres_datadir:/var/lib/postgresql/data"
volumes:
  btcpay_datadir: 
  postgres_datadir: 
  nbxplorer_datadir: 
networks: {}
```
