### ISSUE TITLE
CI for BtcPayServer Builds

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver#365]
Add some CI  so that we can make sure we do not break the stable version of btcpayserver.

Requirments:

- Run CI on commits to develop and pull requests
- Build project with dotnet sdk 
- Run tests with dotnet sdk( you will need to run the docker compose 

I've been trying to do this with CircleCI but the dotnet tests project goes unresponsive after it starts running. Any pointers would be appreciated

```yml
version: 2
jobs:
  build:
    machine: 
      docker_layer_caching: true
    steps: 
      - checkout
      - run: docker build .
  test:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            lsb_release -a
            wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get install apt-transport-https
            sudo apt-get update
            sudo apt-get install dotnet-sdk-2.1
            cd BTCPayServer.Tests
            docker-compose up -d
            sleep 60
            docker ps
            dotnet test


workflows:
  version: 2
  build_and_test:
    jobs:
      - test

```
