### ISSUE TITLE
[Bug]: Multiple Clearnet IPs (IPv4 and IPv6) leads to disabled tab in Public Node Info View

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver#4245]
### What is your BTCPay version?

BTCPay 1.6.12.0

### How did you deploy BTCPay Server?

Docker

### What happened?

I have enabled C-Lightning and this custom fragment to also expose my IPv6 address:

```
version: "3"

services:
  clightning_bitcoin:
    environment:
      LIGHTNINGD_OPT: |
         announce-addr=[2a03:4000:6:b1::2]
```

As a result I get a Public Node Info page with 3 tabs, but the middle one with my IPv6 is not clickable:
https://btcpay.4sats.net/embed/EFHayf8AAHe9hxXhUd4uvzmHsShm6PS2SBvFbg9pDJXq/BTC/ln

### How did you encounter this bug?

1. install the fragment
2. click on the Public Node Info link in the GUI
3. try to click on the middle tab to see my IPv6 (boom)

### Relevant log output

```shell
there is none
```

### What browser do you use?

Microsoft Edge 107 on Mac OS

### Are you sure this is a bug report?

- [X] I confirm this is a bug report
