### ISSUE TITLE
[Bug]: If PoS item code contains a /, LNUrl would not work

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/btcpayserver#4601]
### What is your BTCPay version?

1.7.5

### How did you deploy BTCPay Server?

docker

### What happened?

If a PoS has an item whose code contains a `/`, the generated LNURL wouldn't work.

### How did you encounter this bug?

1. Create a PoS with the following item:

```yml
btc vancity meetup 007 w/ seb bunney:
  title: BTC Vancity MeetUp 007 w/ Seb Bunney
  price: 1
  description: "Entrance ticket for BTC VanCity 007 w/ Seb Bunney."
  image: ~/img/pos-sample/green-tea.jpg
  price_type: fixed
  disabled: false
  inventory: 200
```

2. Then select print view, and save.
3. Try to pay to this item through LNUrl.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report
