### ISSUE TITLE
[Bug]: Advanced rate rules: code preview line height broken

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/btcpayserver#4920]
### What is your BTCPay version?

v1.9.1

### How did you deploy BTCPay Server?

docker

### What happened?

The advanced rating rule examples have a styling issue, some border overlapping?

![image](https://user-images.githubusercontent.com/1136761/234619194-299e4f79-28ec-4547-ab0e-4857d248d49d.png)

### How did you encounter this bug?

Store -> Settings -> Rates -> toggle "Advanced rating rule script" and click on the (i) icon to show examples.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by ndeet** [comment]
this code (copied from browser debug) is causing it:

```css
pre.text-wrap, pre:not(.text-wrap) code {
    padding: var(--btcpay-space-m) !important;
}
```
