### ISSUE TITLE
No product ID in response of invoice request

### ISSUE THREAD

**Issue by Janaka-Steph** [btcpayserver/btcpayserver#779]
**Describe the problem/bug**
I have a PoS app with notification url callback which gives me the invoiceId. Then when I `GET /invoices/:invoiceId` I would like to have the product ID. 
But `itemDesc` contains only the title of the product and `itemCode` is empty.

**Example**
Given this PoS template 
```
1:
  price: 0.65
  title: Master Origin Ethiopia
  description: Master Origin Ethiopia tem um aroma a flor de laranjeira.
  image: https://www.nespresso.com/C-0363-Ethiopia-2000x2000.png

2:
  price: 0.65
  title: Fortissio Lungo
  description: Um corpo e aroma intensos.
  image: https://www.nespresso.com/C-0014-2000x2000.png
```

I would like to get `1` in invoice response when product 1 has been selected.

**Your environment**
* Version of BTCPay Server: 1.0.3.94
* Deployment method: docker
